- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - lighttpd
  - spawn-fcgi
  - php5-fpm 
  - php5
  - php5-cgi

- name: create /etc/lighttpd dir 
  sudo: True
  file: path=/etc/lighttpd state=directory

- name: start /etc/init.d/php5-fpm
  sudo: True
  shell: /etc/init.d/php5-fpm start

- name: create bin dir in root
  sudo: True
  file: path=/root/bin state=directory

- name: copy gencert script
  sudo: True
  copy: src=files/root/bin/gencert.sh dest=/root/bin/gencert.sh mode=700 owner=root group=root

- name: copy create-admin script
  sudo: True
  copy: src=files/root/bin/create-md5sum.pl dest=/root/bin/create-md5sum.pl mode=700 owner=root group=root

- name: create cert in /etc/lighttpd
  sudo: True
  shell: /root/bin/gencert.sh /etc/lighttpd/lighttpd.pem

- name: copy php directory
  sudo: True
  copy: src=files/etc/php5 dest=/etc/php5 owner=root group=root

- name: put config file in place
  sudo: True
  copy: src=files/etc/lighttpd/lighttpd.conf dest=/etc/lighttpd/lighttpd.conf

- name: set permissions to pi
  sudo: True
  file: path={{ item }} owner=pi group=pi recurse=yes state=directory
  with_items: 
  - /var/www
  - /var/log/lighttpd
  - /var/cache/lighttpd
  - /run/lighttpd

- name: copy auth file
  sudo: True
  copy: src=files/etc/lighttpd/lighttpd.user dest=/etc/lighttpd/lighttpd.user mode=640 owner=root group=pi

- name: start lighttpd daemon 
  sudo: True
  shell: /etc/init.d/lighttpd restart
