- name: create /etc/admin dir 
  sudo: True
  file: path=/etc/admin state=directory

- name: create www dir 
  file: path=/var/www state=directory owner=pi group=pi mode=755

- name: clone repo to www dir
  git: repo=git@github.com:fliphess/raspi-admin-panel.git dest=/var/www/ update=yes accept_hostkey=yes force=yes

- name: put config file in place
  sudo: True
  copy: src=settings.yml dest=/etc/admin/settings.yaml owner=pi group=pi mode=644

- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - python-yaml

- name: set +x for cgi scripts
  sudo: True
  file: path={{ item }} mode=0755
  with_items:
    - /var/www/admin/index.cgi
    - /var/www/admin/input.cgi    
    - /var/www/admin/reset.cgi
    - /var/www/admin/system.cgi
    - /var/www/admin/tools/env.cgi
    - /var/www/admin/tools/upload.cgi
