---

/etc/security/limits.conf:
@audio - rtprio 80
@audio - memlock unlimited
@audio - nice -10


/etc/nsswitch.conf:
hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4


/etc/rc.local:
/opt/musicbox/startup.sh


etc/modprobe.d/alsa-base.conf:
options snd-usb-audio index=-2 
options snd-usb-audio index=-2 nrpacks=1


/etc/modules:
snd_bcm2835
snd_soc_bcm2708_i2s
bcm2708_dmaengine
snd_soc_pcm5102a
snd_soc_hifiberry_dac
ipv6
bcm2708_wdog
snd_soc_hifiberry_digi



/etc/libao.conf: 
default_driver=alsa
dev=default
use_mmap=no
