---
- name: get python-apt
  sudo: True
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y install python-apt; touch /root/.python-apt-done
    creates=/root/.python-apt-done

- name: Don't install recommends
  sudo: true
  lineinfile: dest=/etc/apt/apt.conf line='APT::Install-Recommends "0";' create=yes
  notify: apt-get-update

- name: Don't install suggests
  sudo: true
  lineinfile: dest=/etc/apt/apt.conf line='APT::Install-Suggests "0";'
  notify: apt-get-update

- name: add rpi repo
  sudo: true
  apt_repository: repo='deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi' state=present
  notify: apt-get-update

- name: add rpi sources
  sudo: true
  apt_repository: repo='deb-src http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi' state=present
  notify: apt-get-update
