---
- name: set boot options in cmdline.txt
  sudo: true
  replace: dest=/boot/cmdline.txt regexp='^dwc_otg.lpm_enable=0 (.*)$' replace='dwc_otg.fiq_fix_enable=1 dwc_otg.fiq_split_enable=0 dwc_otg.lpm_enable=0 smsc95xx.turbo_mode=N init=/bin/systemd \1' 

- name: put config.txt in place 
  sudo: true
  copy: src=config.txt dest=/boot/config.txt owner=root group=root

- name: Make server make better use of ram instead of disk
  sudo: true
  lineinfile: dest=/etc/default/rcS line="RAMRUN=yes"

- name: Make server use ram instead of disk
  sudo: true
  lineinfile: dest=/etc/default/rcS line="RAMLOCK=yes"

- name: set swappiness
  sudo: true
  sysctl: name=vm.swappiness value=0 state=present sysctl_file=/etc/sysctl.d/raspbian.conf reload=no
  notify: reload-sysctl

- name: set vm.min_free
  sudo: true
  sysctl: name=vm.min_free_kbytes value=32768 state=present sysctl_file=/etc/sysctl.d/raspbian.conf reload=no
  notify: reload-sysctl
