- name: disable ipv6
  sudo: True
  shell: echo "net.ipv6.conf.all.disable_ipv6 = 1" > /etc/sysctl.d/ipv6.conf && /sbin/sysctl -p creates=/etc/sysctl.d/ipv6.conf

- name: turn off swap
  sudo: True
  shell: echo "vm.swappiness = 0" > /etc/sysctl.d/swap.conf && /sbin/sysctl -p creates=/etc/sysctl.d/swap.conf

- name: bootscripts
  sudo: True
  copy: files/etc/rc.local dest=/etc/rc.local owner=root group=root
  
- name: configure ssh
  sudo: True
  shell: update-rc.d ssh enable && invoke-rc.d ssh start
  
- name: enable systemd
  sudo: True
  shell: sed -i 's/$/ init=\/bin\/systemd/' /boot/cmdline.txt
  
- name: put motd in place
  sudo: True
  copy: src=files/etc/motd dest=/etc/motd mode=644 group=root owner=root

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart sshd

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart sshd

handlers:
  - name: Restart sshd
    action: service name=sshd state=restarted


