- name: copy binary in place 
  sudo: True
  copy: src=motion/motion-mmal dest=/usr/local/bin/motion-mmal mode=755 owner=pi group=pi

- name: copy config in place 
  sudo: True
  copy: src=motion/motion-mmalcam.conf dest=/etc/motion/motion-mmalcam.conf mode=740 owner=pi group=pi

- name: put /etc/default/motion-mmal in place
  sudo: True
  copy: src=etc/default/motion-mmal dest=/etc/default/motion-mmal mode=755 owner=root group=root

- name: create storage directory 
  sudo: True
  file: path=/home/pi/video state=directory mode=0750 owner=pi group=pi

- name: copy init script in place
  sudo: True
  copy: src=etc/init.d/motion-mmal dest=/etc/init.d/motion-mmal mode=755 owner=root group=root
  notify:
    - start-motion-mmal
    - start-motion-mmal-at-boot
    - stop-motion-daemon
    - stop-motion-daemon-at-boot
