- name: update firmware
  sudo: true
  shell: rpi-update

- name: put interfaces file in place
  sudo: true
  copy: src=etc/network/interfaces dest=/etc/network/interfaces owner=root group=root

- name: bootscripts
  sudo: true
  copy: src=etc/rc.local dest=/etc/rc.local owner=root group=root
  
- name: configure ssh
  sudo: true
  shell: update-rc.d ssh enable && invoke-rc.d ssh start
  
- name: put motd in place
  sudo: true
  copy: src=etc/motd dest=/etc/motd mode=644 group=root owner=root

- name: create bin dir in root
  sudo: true
  file: path=/root/bin state=directory

- name: Remove sudo group rights
  sudo: true
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Set ssh auth sudo rights 
  sudo: true
  action: 'lineinfile dest=/etc/sudoers.d/ssh line="Defaults env_keep+=SSH_AUTH_SOCK" create=yes'

- name: set sudo rights
  sudo: true
  action: 'lineinfile dest=/etc/sudoers.d/pi line="pi      ALL=NOPASSWD: ALL" create=yes'

- name: Turn on ssh at boot time
  sudo: true
  shell: update-rc.d {{ item }} defaults
  with_items:
  - ssh
  - ntp
