- name: install required packages 
  sudo: True
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - samba
  - samba-common-bin
  - swat
  - dnsmasq

- name: set network configuration 
  sudo: True
  copy: src=files/etc/network/interfaces dest=/etc/network/ mode=744 owner=root group=root
